tenant:
  hostname: "env209597.int-az-eu.webmethods.io"   # webMethodsIO Integration hostname or ip address
  port: "443"                                       # webMethodsIO Integration port
  admin_username: "refplatform"                     # webMethodsIO Integration user  
  type: "dev"                                         #DEV