tenant:
  hostname: "insrsaaz.int-az-eu.webmethods.io"   # webMthodsIO Integration hostname or ip address
  port: "443"                                       # webMthodsIO Integration port
  admin_username: "refplatform"                     # webMthodsIO Integration user
  type: "play"                                         #Dev